# source guard: no `$` on catalog/pack/tensor lists (parse-token exact)

R_FILES <- local({
  files <- list.files(
    testthat::test_path("..", "..", "R"),
    pattern = "\\.R$",
    full.names = TRUE
  )
  # generated by Rcpp::compileAttributes(), not hand-edited
  files[basename(files) != "RcppExports.R"]
})

# parsed once with sources kept. both tests below reuse it.
R_PARSED <- stats::setNames(
  lapply(R_FILES, parse, keep.source = TRUE),
  basename(R_FILES)
)

# every `$` operator token in a parsed file, as "file:line"
dollar_sites <- function(exprs, label) {
  pd <- utils::getParseData(exprs)
  hits <- pd[pd[["token"]] == "'$'", "line1"]
  if (!length(hits)) {
    return(character(0))
  }
  paste0(label, ":", hits)
}

# scan every parsed file with `f`, which takes (exprs, label)
scan_sources <- function(f) {
  unlist(
    Map(f, R_PARSED, names(R_PARSED)),
    use.names = FALSE
  )
}

# cli calls that put their strings in front of a user
MSG_CALLS <- c(
  "cli_abort",
  "cli_warn",
  "cli_inform",
  "cli_bullets",
  "cli_alert_info",
  "cli_verbatim",
  "format_inline"
)

# every string literal inside a cli message call, however deeply nested
msg_strings <- function(e) {
  if (!is.call(e)) {
    return(character(0))
  }
  fn <- e[[1L]]
  # cli::cli_abort() parses as `::`(cli, cli_abort)
  nm <- if (is.call(fn) && identical(as.character(fn[[1L]]), "::")) {
    as.character(fn[[3L]])
  } else if (is.name(fn)) {
    as.character(fn)
  } else {
    ""
  }
  rest <- unlist(lapply(as.list(e)[-1L], msg_strings), use.names = FALSE)
  if (nm %in% MSG_CALLS) {
    return(c(all_strings(e), rest))
  }
  rest
}

all_strings <- function(e) {
  if (is.character(e)) {
    return(e)
  }
  if (!is.call(e)) {
    return(character(0))
  }
  unlist(lapply(as.list(e), all_strings), use.names = FALSE)
}

# public message text carrying a banned character (R3)
banned_msg_sites <- function(exprs, label) {
  found <- unlist(lapply(exprs, msg_strings), use.names = FALSE)
  bad <- found[grepl("--|;", found)]
  if (!length(bad)) {
    return(character(0))
  }
  paste0(label, ": ", bad)
}

# a bait file the scanner must classify correctly
bait_parsed <- function(lines) {
  path <- withr::local_tempfile(fileext = ".R", .local_envir = parent.frame())
  writeLines(lines, path)
  parse(path, keep.source = TRUE)
}

# scans read R/*.R sources. this file is .Rbuildignore'd so it never ships in a tarball.

test_that("no `$` access anywhere in R/, and the guard fires", {
  expect_equal(scan_sources(dollar_sites), character(0))

  bait <- bait_parsed(c(
    '# a comment mentioning $ and a regex "\\\\.qs2$"',
    'f <- function(e) e[["ok"]]',
    'g <- function(e) e$covariates'
  ))
  # the comment and the regex must not count -- the one real access must
  expect_equal(length(dollar_sites(bait, "bait")), 1L)
})

test_that("no `--` or `;` in public message text, and the guard fires", {
  expect_equal(scan_sources(banned_msg_sites), character(0))

  bait <- bait_parsed(c(
    '# a comment with -- and a ; in it',
    'f <- function() stop("dev-facing -- still allowed", call. = FALSE)',
    'g <- function() cli::cli_abort("a -- b", call = NULL)',
    'h <- function() cli::cli_warn(c("ok", "i" = "x; y"), call = NULL)'
  ))
  # the comment and the plain stop() must not count -- the two cli calls must
  expect_equal(length(banned_msg_sites(bait, "bait")), 2L)
})
