# source guard: no `$` on catalog/pack/tensor lists (parse-token exact)

# every `$` operator token in a file, as "file:line"
dollar_sites <- function(path) {
  pd <- utils::getParseData(parse(path, keep.source = TRUE))
  hits <- pd[pd[["token"]] == "'$'", "line1"]
  if (!length(hits)) {
    return(character(0))
  }
  paste0(basename(path), ":", hits)
}

test_that("no `$` access anywhere in R/", {
  files <- list.files(
    testthat::test_path("..", "..", "R"),
    pattern = "\\.R$",
    full.names = TRUE
  )
  # generated by Rcpp::compileAttributes(), not hand-edited
  files <- files[basename(files) != "RcppExports.R"]
  expect_equal(
    unlist(lapply(files, dollar_sites), use.names = FALSE),
    character(0)
  )
})

test_that("the `$` guard actually fires", {
  bait <- withr::local_tempfile(fileext = ".R")
  writeLines(
    c(
      '# a comment mentioning $ and a regex "\\\\.qs2$"',
      'f <- function(e) e[["ok"]]',
      'g <- function(e) e$covariates'
    ),
    bait
  )
  # the comment and the regex must not count -- the one real access must
  expect_equal(length(dollar_sites(bait)), 1L)
})
