// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// col_stats
List col_stats(NumericMatrix obj);
RcppExport SEXP _methylCIPHERv2_col_stats(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(col_stats(obj));
    return rcpp_result_gen;
END_RCPP
}
// fill_imp_col
void fill_imp_col(NumericMatrix obj, NumericVector mean_vec);
RcppExport SEXP _methylCIPHERv2_fill_imp_col(SEXP objSEXP, SEXP mean_vecSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type obj(objSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mean_vec(mean_vecSEXP);
    fill_imp_col(obj, mean_vec);
    return R_NilValue;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_methylCIPHERv2_col_stats", (DL_FUNC) &_methylCIPHERv2_col_stats, 1},
    {"_methylCIPHERv2_fill_imp_col", (DL_FUNC) &_methylCIPHERv2_fill_imp_col, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_methylCIPHERv2(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
