# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_stats <- function(obj, cols = NULL, row_moments = FALSE) {
    .Call(`_methylCIPHERv2_col_stats`, obj, cols, row_moments)
}

fill_imp_col <- function(obj, mean_vec) {
    invisible(.Call(`_methylCIPHERv2_fill_imp_col`, obj, mean_vec))
}

